server:
  port: 9000
spring:
  application:
    name: "reporting-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
logging:
  level:
    co.com.pragma: "trace"
aws:
  region: ${AWS_REGION}
  dynamodb:
    endpoint: "http://localhost:8000"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
      base-path: "/reporting/actuator"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
entrypoint:
  sqs:
    region: ${AWS_REGION}
    queueUrl: ${AWS_SQS_REPORTES}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
jwt:
  secret: ${JWT_SECRET}
services:
  request:
    url: "http://localhost:8090"
  auth:
    url: "http://localhost:8080"
adapter:
  sqs:
    region: ${AWS_REGION}
    queues:
      notifications: ${AWS_SQS_NOTIFICACIONES}

queue:
  names:
    notifications: notifications
job:
  auth:
    email: ${REPORT_EMAIL}
    password: ${REPORT_PASSWORD}

app:
  timezone: America/Lima
scheduler:
  daily-report:
    cron: 0 0 3 * * ?

springdoc:
  swagger-ui:
    path: /reporting/swagger-ui.html
  api-docs:
    path: /reporting/v3/api-docs
